In [1]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

C:\Users\murug\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\murug\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
C:\Users\murug\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)

In [2]:

from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import LabelEncoder
from collections import defaultdict
from nltk.corpus import wordnet as wn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score

In [29]:
print(os.getcwd())  
os.chdir(r'C:\\Users\\murug\\Desktop\\Jey\\GMU\\Semester 3\\DAEN 690\\mimic-iii-clinical-database-1.4\\allcsv')

C:\Users\murug\Desktop\Jey\GMU\Semester 3\DAEN 690\mimic-iii-clinical-database-1.4\allcsv

In [4]:
NOTEEVENTS=pd.read_csv('NOTEEVENTS.csv',dtype={'ROW_ID':np.int32, 'SUBJECT_ID': np.int32,'HADM_ID': np.float64,
                                       'CHARTDATE':str,'STORETIME':str,'CHARTTIME':str,
                                       'STORETIME': str,'CATEGORY': str,'DESCRIPTION':str,'CGID':str,'ISERROR':str,
                                        'TEXT':str}, parse_dates=['CHARTDATE'])
DIAGNOSES_ICD=pd.read_csv('DIAGNOSES_ICD.csv',dtype={'ROW_ID':np.int32, 'SUBJECT_ID': np.int32,'HADM_ID': np.int32,
                                            'SEQ_NUM':  np.float64,'ICD9_CODE':str})

In [5]:
NOTEEVENTS.head()

,ROW_ID,SUBJECT_ID,HADM_ID,CHARTDATE,CHARTTIME,STORETIME,CATEGORY,DESCRIPTION,CGID,ISERROR,TEXT
0,174,22532,167853.0,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...
1,175,13702,107527.0,2118-06-14,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2118-6-2**] Discharg...
2,176,13702,167118.0,2119-05-25,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2119-5-4**] D...
3,177,13702,196489.0,2124-08-18,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2124-7-21**] ...
4,178,26880,135453.0,2162-03-25,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2162-3-3**] D...

In [6]:
DIAGNOSES_ICD.head()

   ROW_ID  SUBJECT_ID  HADM_ID  SEQ_NUM ICD9_CODE
0    1297         109   172335      1.0     40301
1    1298         109   172335      2.0       486
2    1299         109   172335      3.0     58281
3    1300         109   172335      4.0      5855
4    1301         109   172335      5.0      4254

In [28]:
print('Null Values in NOTEEVENTS :\n\n',NOTEEVENTS.isnull().sum(axis = 0))
print('\n')
print('Null Values in DIAGNOSES_ICD :','\n\n',DIAGNOSES_ICD.isnull().sum(axis = 0))

Null Values in NOTEEVENTS :

 ROW_ID               0
SUBJECT_ID           0
HADM_ID         231836
CHARTDATE            0
CHARTTIME       316566
STORETIME       836776
CATEGORY             0
DESCRIPTION          0
CGID            836776
ISERROR        2082294
TEXT                 0
dtype: int64


Null Values in DIAGNOSES_ICD :

 ROW_ID         0
SUBJECT_ID     0
HADM_ID        0
SEQ_NUM       47
ICD9_CODE     47
dtype: int64

In [27]:

print('NOTEEVENTS Total HADM ID count : ', NOTEEVENTS.HADM_ID.count())
print('NOTEEVENTS Unique HADM ID count : ', NOTEEVENTS.HADM_ID.nunique())
print('\n')
print('DIAGNOSES_ICD Total HADM ID count : ' , DIAGNOSES_ICD.HADM_ID.count())
print('DIAGNOSES_ICD Unique HADM ID count : ', DIAGNOSES_ICD.HADM_ID.nunique())
print('\n')
print('DIAGNOSES_ICD Total ICD9 Code count : ' , DIAGNOSES_ICD.ICD9_CODE.count())
print('DIAGNOSES_ICD Unique ICD9 Code count : ', DIAGNOSES_ICD.ICD9_CODE.nunique())

NOTEEVENTS Total HADM ID count :  1851344
NOTEEVENTS Unique HADM ID count :  58361


DIAGNOSES_ICD Total HADM ID count :  651047
DIAGNOSES_ICD Unique HADM ID count :  58976


DIAGNOSES_ICD Total ICD9 Code count :  651000
DIAGNOSES_ICD Unique ICD9 Code count :  6984

In [39]:
len(NOTEEVENTS.TEXT[39932])

14739

In [10]:
NOTEEVENTS.TEXT[15]

"Admission Date:  [**2203-11-3**]              Discharge Date:   [**2203-11-12**]\n\nDate of Birth:  [**2161-11-27**]             Sex:   M\n\nService: MEDICINE\n\nAllergies:\nPenicillins\n\nAttending:[**First Name3 (LF) 348**]\nChief Complaint:\nShortness of breath, chest pain\n\nMajor Surgical or Invasive Procedure:\nPericardiocentesis\nEGD with biopsy\n\n\nHistory of Present Illness:\n41 y/o M w/ h/o HIV/AIDS (HIV dx 83, AIDS 92, last CD4 132, VL\n>100K [**10/2203**], RF IVDU), not currently on HAART, previous right\nsided bacterial endocarditis with residual 4+ TR, h/o prior MI\nin [**2193**], who presents from [**Hospital **] Hospital for emergent\nevaluation of pericardial tamponade.\n\nPatient was recently hospitalized at [**Hospital1 18**] for osteomyelitis of\nhis L-ankle s/p prior fall. Presented to ED with fevers and\nankle pain. Taken to OR by ortho and found to have neg\nbrefringent crystals c/w gout. Tissue/Bone cultures grew MSSA.\nPatient started on cefazolin. F/U MRI could not rule out\nosteomyelitis and the patient was discharged to [**Hospital **]\nhospital for 6 weeks of IV cefazolin (to end [**2203-12-5**]).\n\nWhile at [**Hospital1 **], patient had uneventful course until night\nprior to admission when he developed low grade temp to 100.2.\nThe morning of admission patient felt short of breath, lethargic\nwith some chest pain. Noted to be tachycardic by vitals, and\nwith decreased O2 sat to 90% on RA -> 96% 2L NC. Chest CT\nperformed showing massively enlarged cardiac silhouette.\nTransfered to [**Hospital1 18**] for emergent pericardiocentesis.\n\nOn review of symptoms, he denies any prior history of stroke,\nTIA, deep venous thrombosis, pulmonary embolism, bleeding at the\ntime of surgery, myalgias, joint pains, cough, hemoptysis, black\nstools or red stools. He denies recent fevers, chills or rigors.\nHe denies exertional buttock or calf pain. All of the other\nreview of systems were negative.\n\nIn the ED, T98.8, HR 122, BP 147/87, RR 19, O2 97%. Patient\nnoted to be uncomfortable, and w/ rub on exam. Pulsus not\nperformed. Otherwise exam unremarkable. Transferred to cath lab\nfor emergent peridcardiocentesis.\n\nIn cath lab, pericardial pressure 35, RA and [**Name Prefix (Prefixes) **] [**Last Name (Prefixes) 1934**] each\n30, RV systolic 55. 1.2 L of sanguinous fluid drained from the\npericardium. Pericardial pressure decreased to 5mm Hg, and RA to\n18mm Hg s/p drain. Patient admitted to CCU for further\nmanagement.\n\n\nPast Medical History:\n- HIV/AIDS: HIV dignosed in '[**79**], AIDS diagnosed in '[**88**], last CD4\ncount 132, VL 100K [**2202-7-26**]. Perscribed HAART but pt reports\nnoncompliance for past 5 months (followed by Dr [**Last Name (STitle) 2219**] at [**Hospital1 2177**]\nand NP [**Doctor Last Name **] [**Telephone/Fax (1) 2218**]) -- ONLY FATHER KNOWS DIAGNOSIS.\n- Hep C\n- Hep B cleared\n- Myocardial infarction in [**2193**]\n- h/o endocarditits with grade 4 TR - approximately 12 years ago\n\n- Recurrent epididimitis\n- h/o IVDU on methadone 80 mg QD (followed at Baycove\n[**Telephone/Fax (1) 2217**])\n- Asthma\n- osteomyelitis (MSSA) on cefazolin\n\n\nSocial History:\nPt was most recently living at [**Hospital1 **].  He has a girlfriend.\n[**Name (NI) **] denies tobacco, EtOH, and current drug use/abuse.  He is in a\nmethadone program because of past IVDU.\n\n\nFamily History:\nNC\n\nPhysical Exam:\nON ADMISSION:\nVS: T 99.3, BP 132/72 , HR 105 , RR 20, O2 99% 2l NC\nGen: Caucasion male w/ mild bitemporal wasting resting\ncomfortably in bed.\nHEENT: NCAT. Sclera anicteric. PERRL, EOMI. Conjunctiva were\npink, no pallor or cyanosis of the oral mucosa.\nNeck: Supple. Unable to appreciate JVD as prominent carotid\npulses b/l.\nCV: PMI located in 5th intercostal space, midclavicular line.\nRR, normal S1, S2. +2/6 SEM at LUSB.\nChest: Pericardial drain in place, clean, dry, intact, No\nscoliosis or kyphosis. Resp were unlabored, no accessory muscle\nuse. Sparse basilar crackles right > left.\nAbd: +BS, softly distended, non-tender, liver edge palpable\nbelow the costal margin. No abdominial bruits.\nExt: R-AKA. Left ankle in cast, 2+ DP pulse. No c/c/e. No\nfemoral bruits. +line in L-groin, no bleeding, no hematoma.\nSkin: No stasis dermatitis, ulcers, scars, or xanthomas.\nPulses: Right: Carotid 2+ without bruit; Femoral 2+ without\nbruit; 2+ DP\nLeft: Carotid 2+ without bruit; Femoral 2+ without bruit\nON DISCHARGE:\nVS: 98.1  117/89  118  20  95% RA\nExam was largely unchanged.  Abdomen was mildly distended, not\ntender, normoactive bowel sounds.  His cardiac exam was\nunchanged, the pericardial drain was pulled on day 2 of\nadmission.  Lungs were clear to auscultation bilaterally. Wound\nvac was in place, with minimal drainage.\n\n\nPertinent Results:\n[**2203-11-3**] 05:00PM OTHER BODY FLUID  TOT PROT-6.1 GLUCOSE-69\nLD(LDH)-650 AMYLASE-56 ALBUMIN-1.9\n[**2203-11-3**] 05:00PM OTHER BODY FLUID  WBC-2122* HCT-11* POLYS-56*\nLYMPHS-27* MONOS-13* EOS-2* METAS-2*\n[**2203-11-3**] 03:58PM   LACTATE-3.2*\n[**2203-11-3**] 03:50PM   GLUCOSE-126* UREA N-38* CREAT-1.8*\nSODIUM-132* POTASSIUM-4.8 CHLORIDE-98 TOTAL CO2-25 ANION GAP-14\n[**2203-11-3**] 03:50PM   estGFR-Using this\n[**2203-11-3**] 03:50PM   CK(CPK)-29*\n[**2203-11-3**] 03:50PM   cTropnT-<0.01\n[**2203-11-3**] 03:50PM   CK-MB-NotDone\n[**2203-11-3**] 03:50PM   WBC-6.2 RBC-3.09* HGB-9.2* HCT-28.6* MCV-93\nMCH-29.6 MCHC-32.0 RDW-19.5*\n[**2203-11-3**] 03:50PM   NEUTS-77.3* LYMPHS-17.1* MONOS-5.3 EOS-0.1\nBASOS-0.2\n[**2203-11-3**] 03:50PM   PLT COUNT-295#\n[**2203-11-3**] 03:50PM   PT-15.1* PTT-38.2* INR(PT)-1.4*\n\nPericardial fluid: NEGATIVE FOR MALIGNANT CELLS.\n.\nECHO ([**2203-11-3**]) Pre-pericardiocentesis: The left atrium is\nelongated. The estimated right atrial pressure is >20 mmHg. The\nleft ventricular cavity is unusually small. Regional left\nventricular wall motion is normal. Left ventricular systolic\nfunction is hyperdynamic (EF>75%). The right ventricular cavity\nis moderately dilated. There is a large circumferential\npericardial effusion. Stranding is visualized within the\npericardial space c/w some organization. There is left atrial\ndiastolic collapse. There is right ventricular diastolic\ncollapse, consistent with impaired fillling/tamponade\nphysiology. There is significant, accentuated respiratory\nvariation in mitral/tricuspid valve inflows, consistent with\nimpaired ventricular filling.\n\nCompared with the prior study (images reviewed) of [**2203-10-20**],\nlarge pericardial effusion with echocardiographic signs of\ntamponade is new.\n.\nECHO ([**2203-11-3**]) Post pericardiocentesis: The left atrium is\nelongated. The right atrium is markedly dilated. There is mild\nsymmetric left ventricular hypertrophy with normal cavity size\nand systolic function (LVEF>55%). The right ventricular cavity\nis markedly dilated. Right ventricular systolic function is\nnormal. [Intrinsic right ventricular systolic function is likely\nmore depressed given the severity of tricuspid regurgitation.]\nThere is abnormal septal motion/position consistent with right\nventricular pressure/volume overload. There is no aortic valve\nstenosis. The mitral valve leaflets are mildly thickened. There\nis partial flail of a tricuspid valve leaflet. The tricuspid\nvalve leaflets fail to fully coapt. Severe [4+] tricuspid\nregurgitation is seen. There is mild pulmonary artery systolic\nhypertension. There is a trivial/physiologic pericardial\neffusion.\n\nCompared with the prior study (images reviewed) of [**2203-11-3**],\nthe residue pericardial effusion is minimal.\n.\nCardiac catherization ([**2203-11-3**]):\n1. Large circumferential pericardial effusion with tamponade\nphysiology.\n2. Successful pericardiocentesis with drainage of 1500mls of\nblood\nstained fluid. Patient left cathlab in stable condition\nFINAL DIAGNOSIS:\n1. Severe pericardial tamponade.\n2. Mild primary pulmonary hypertension.\n3. Successful pericardiocentesis with drainage of 1500ml of\nblood\nstained fluid.\n.\nECHO ([**2203-11-4**]): The left atrium is mildly dilated. The right\natrium is markedly dilated. There is mild symmetric left\nventricular hypertrophy with normal cavity size and\nregional/global systolic function (LVEF>55%). Transmitral and\ntissue Doppler imaging suggests normal diastolic function, and a\nnormal left ventricular filling pressure (PCWP<12mmHg). The\nright ventricular cavity is moderately dilated. Right\nventricular systolic function is borderline normal [intrinsic\nfunction is likely depressed given the severity of tricuspid\nregurgitation.]. There is abnormal diastolic septal\nmotion/position consistent with right ventricular volume\noverload. The aortic valve leaflets (3) appear structurally\nnormal with good leaflet excursion. Trace aortic regurgitation\nis seen. The mitral valve appears structurally normal with\ntrivial mitral regurgitation. The tricuspid valve leaflets are\nmildly thickened and appear shortened/remnants that do not fully\ncoapt. A small echodensity is seen on the right atrial side of\nthe septal leaflet - ?vegetation ?old vs. partial flail of\nleaflet segment. Severe [4+] tricuspid regurgitation is seen.\nThere is a small (<1cm), circumferential, partially echo filled\npericardial effusion without evidence of hemodynamic compromise.\n\nCompared with the prior study (post-pericardiocentesis, images\nreviewed) of [**2203-11-3**], the findings are similar.\n.\nECHO ([**2203-11-5**]): The left atrium is mildly dilated. The right\natrium is moderately dilated. There is mild symmetric left\nventricular hypertrophy with normal cavity size and systolic\nfunction (LVEF>55%). The right ventricular cavity is moderately\ndilated. Right ventricular systolic function is borderline\nnormal. The mitral valve appears structurally normal with\ntrivial mitral regurgitation. The tricuspid valve leaflets are\nmildly thickened and appear shortened/remnants and fail to fully\ncoapt. A small echodensity is again seen on the right atrial\nside of the septal leaflet which could be either a vegeateion or\na partial leaflet segment. Severe [4+] tricuspid regurgitation\nis seen. There is a small pericardial effusion. The effusion is\necho dense, consistent with blood, inflammation or other\ncellular elements. There are no echocardiographic signs of\ntamponade.\n\nCompared with the prior study (images reviewed) of [**2203-11-4**],\nthe pericardial effusion is slightly smaller and may be more\necho dense. The left ventricular cavity size is probably\nslightly larger (reflecting better filling). The small\nechodensity on the tricuspid leaflet has not changed in size.\n.\nECHO ([**2203-11-8**]): The left atrium is mildly dilated. The right\natrium is dilated. There is mild symmetric left ventricular\nhypertrophy. The left ventricular cavity size is normal. Overall\nleft ventricular systolic function is normal (LVEF>55%). The\nright ventricular cavity is dilated. Right ventricular systolic\nfunction is normal. [Intrinsic right ventricular systolic\nfunction is likely more depressed given the severity of\ntricuspid regurgitation.] There is abnormal septal\nmotion/position consistent with right ventricular\npressure/volume overload. The aortic valve leaflets (3) appear\nstructurally normal with good leaflet excursion. The mitral\nvalve appears structurally normal with trivial mitral\nregurgitation. The tricuspid valve leaflets fail to fully coapt.\nSevere [4+] tricuspid regurgitation is seen. There is a\ntrivial/physiologic pericardial effusion. There are no\nechocardiographic signs of tamponade.\n\nCompared with the prior study (images reviewed) of [**2203-11-5**],\npericardial effusion now appears slightly smaller.\n.\nECHO ([**2203-11-11**]):\nThe right atrium is markedly dilated. There is mild symmetric\nleft ventricular hypertrophy with normal cavity size and\nsystolic function (LVEF>55%). The right ventricular cavity is\nmoderately dilated. Right ventricular systolic function is\nborderline normal. The mitral valve leaflets are structurally\nnormal. The tricuspid valve leaflets are mildly thickened. The\ntricuspid valve leaflets fail to fully coapt. There is a very\nsmall, partially echo filled pericardial effusion.\n\nCompared with the prior study (images reviewed) of [**2203-11-8**],\nthe findings are similar.\n\n\nBrief Hospital Course:\n41 year old male with HIV/AIDS, previous R-sided endocarditis\nand severe TR, presented in cardiac tamponade from\nrehabilitation.\n\nCARDIAC TAMPONADE:  On admission, he was transferred to the\ncardiac catherization lab, where over one liter of fluid was\ndrained from his pericardial space.  The fluid was sent for gram\nstain, culture, AFB, [**Doctor First Name **], TB PCR as well as viral studies and\ncytology.  A pericardial drain was initially left in place, but\ngiven minimal drainage over 24 hours, was pulled prior to his\ntransfer to the floor.  The etiology of the pericardial effusion\nis unknown.  He was followed by Cardiology on the floor and the\ninitial plan was for a pericardial window, for both tissue and\nto prevent reaccumulation of fluid.  The patient refused the\nprocedure at this time.  He will follow up as an outpatient to\nre-evaluate for the procedure.  The effusion was followed by\nserial ECHO while the patient was in the hospital.  There was no\nevidence of re-accumulation.  He is scheduled for an outpatient\nECHO in several weeks to evaluate the pericardial space for\nreaccumlation of effusion.\n\nATRIAL FIBRILLATION/FLUTTER: Per multiple EKGs, the patient\nappears to have developed new a fib/flutter.  Given his guaiac\npositive stools, it is not advisable to start anticoagulation at\nthis time.  The patient is being rate controlled on a low dose\nof beta-blocker, which appears to be effective.  He will be\nfollowed by outpatient Cardiology.\n\nANEMIA: The patient had a hematocrit drop during this admission.\n His lab studies are consistent with anemia of chronic disease,\nhowever, the patient was found to have guaiac positive stools.\nGI was consulted and recommeded colonoscopy and EGD.  The\npatient was unable to tolerate the prep and thus the colonoscopy\nwas cancelled.  His EGD demonstrated gastritis and thrush.  He\nwas started on fluconazole to treat the thrush.  He was also\ntransfused two units of packed red blood cells with an\nappropriate hematocrit response.\n\nHIV/AIDS:  The patient had a CD4 count checked during his last\nadmission, it was found to be 132 with a viral load >100K.\nGiven his past noncompliance with HAART therapy and the risk of\ndeveloping drug resistant HIV,  HAART was not restarted.  Pt is\nwilling to restart HARRT, and the plan remains to restart\nmedications at rehabilitation.  Bactrim was continued for PCP\n[**Name Initial (PRE) 1102**].\n\nOSTEOMYELITIS:  The patient was previously admitted for left\nankle pain.  He was followed previously by both the orthopedic\nand ID services.  Both services continued to follow the patient\non this admission.  The patient was continued on 6 weeks of IV\nantibiotics (last day of cefazolin [**2203-12-5**]), although the dose\nwas decreased to 1g q6 because of a low white blood count.\n\nSEVERE TRICUSPID REGURGITATION: Pt with known grade 4 TR and\nflail leaflet which he deveoped after acute bacterial\nendocarditis roughly 10 years ago.  We restarted his lasix and\nspironolactone on this admission.\n\nHCV: HCV viral load checked, and found to be 1.5 million.  No\nfurther therapy initiated.\n\nANXIETY: Pt with history of anxiety and on Klonapin at home.\nHis home regimen was continued.\n\nESOPHAGEAL CANDIDIASIS: Patient was found to have thrush on EGD.\n He was started on a course of fluconazole given his\nimmunosupressed state.  He is being discharged to complete a two\nweek course of anti-fungal medication.\n\n\n\n\n\nMedications on Admission:\ncefazolin 2g IV q8\nmethadone 80mg PO qd (confirmed on prior admit)\nprednisone 10mg qd\nlovenox 40mg SQ\nprilosec 20mg PO qd\nASA 81mg PO daily\ncolace 100mg PO daily\nclonazepam 1mg qAM, 1mg qNoon, 2mg qhs prn\nsennekot 2 tabs PO BID PRN\nmorphine sulfate IR 15mg PO q4 PRN\npromethazine 12.5mg PO q4h PRN\n\n\nDischarge Medications:\n1. Methadone 40 mg Tablet, Soluble Sig: Two (2) Tablet, Soluble\nPO DAILY (Daily).\n2. Heparin (Porcine) 5,000 unit/mL Solution Sig: One (1)\nInjection TID (3 times a day).\n3. Aspirin 81 mg Tablet, Chewable Sig: One (1) Tablet, Chewable\nPO DAILY (Daily).\n4. Docusate Sodium 100 mg Capsule Sig: One (1) Capsule PO DAILY\n(Daily).\n5. Clonazepam 1 mg Tablet Sig: One (1) Tablet PO QAM (once a day\n(in the morning)).\n6. Clonazepam 1 mg Tablet Sig: One (1) Tablet PO Q 12 NOON ().\n7. Clonazepam 1 mg Tablet Sig: Two (2) Tablet PO QHS (once a day\n(at bedtime)) as needed for anxiety.\n8. Senna 8.6 mg Tablet Sig: One (1) Tablet PO BID (2 times a\nday) as needed.\n9. Trimethoprim-Sulfamethoxazole 80-400 mg Tablet Sig: One (1)\nTablet PO DAILY (Daily).\n10. Morphine 15 mg Tablet Sig: One (1) Tablet PO Q4H (every 4\nhours) as needed.\n11. Lactulose 10 gram/15 mL Syrup Sig: Thirty (30) ML PO Q8H\n(every 8 hours) as needed.\n12. Spironolactone 100 mg Tablet Sig: One (1) Tablet PO DAILY\n(Daily).\n13. Furosemide 80 mg Tablet Sig: One (1) Tablet PO DAILY\n(Daily).\n14. Pantoprazole 40 mg Tablet, Delayed Release (E.C.) Sig: One\n(1) Tablet, Delayed Release (E.C.) PO Q12H (every 12 hours).\n15. Metoprolol Tartrate 25 mg Tablet Sig: 0.5 Tablet PO BID (2\ntimes a day).\n16. Fluconazole 200 mg Tablet Sig: One (1) Tablet PO Q24H (every\n24 hours) for 14 days.\n17. Heparin Flush PICC (100 units/ml) 2 ml IV DAILY:PRN\n10 ml NS followed by 2 ml of 100 Units/ml heparin (200 units\nheparin) each lumen Daily and PRN.  Inspect site every shift.\n18. Cefazolin 1 gram Recon Soln Sig: One (1)  Intravenous every\nsix (6) hours for until [**2203-12-5**] weeks: please continue until\n[**2203-12-5**].\n\n\nDischarge Disposition:\nExtended Care\n\nFacility:\n[**Hospital3 7**] & Rehab Center - [**Hospital1 8**]\n\nDischarge Diagnosis:\nPrimary diagnosis:\nCardiac tamponade\nGI Bleeding\nAtrial flutter\n[**Female First Name (un) 564**] esophagitis\n\nSecondary diagnosis:\nPancytopenia\nHIV/AIDS\nHepatitis B and C\nEndocarditits with flail tricuspic valve\nRight heart failure.\nRecurrent epididymitis\nIVDU on methadone 80 mg QD (followed at Baycove [**Telephone/Fax (1) 2217**])\n?Myocardial infarction in [**2193**]\nAsthma\nLLE medial MSSA foot abscess/osteomyelitis.\nGout\nTraumatic Right AKA\nPCP\nAnxiety and depression.\nPPD (+) treated with 6 months INH\n\n\nDischarge Condition:\nStable without fluid reaccumulation per ECHO\n\n\nDischarge Instructions:\nYou were admitted with shortness of breath.  You were\nfound to have fluid around your heart.  The fluid was removed\nbut no specific cause was identified.  If you have any chest\npain or shortness of breath, please alert your doctors\n[**Name5 (PTitle) 2227**].\n\nYou will need weekly labs (specifically CBC, LFTs, BUN, and\nCr) faxed to Dr. [**Known firstname **] [**Last Name (NamePattern1) 1075**] in the Infectious [**Hospital 2228**] clinic at\n[**Hospital1 18**] (fax [**Telephone/Fax (1) 432**]).\n\nYou have a wound VAC on your ankle to help with healing of the\ntissue.  This should be changed every 3 days by the nurses at\nyour facility.  You will need to be seen in the [**Hospital 1957**] clinic to\ndetermine how long you will need to have this in place.\n\nIf you have any symptoms of worsening foot pain, foot redness,\nfevers, chest pain, nausea, vomiting, or any other concerning\nsymptoms you are to go to the emergency room.\n\nMedication changes:\n1. Lasix and spironalactone were restarted during this\nadmission.\n2. You HAART medication was held during this admission.  These\ncan be restarted by your ID doctors [**Name5 (PTitle) 1028**] [**Name5 (PTitle) **] are at rehab.\n3. You are being treated with an antibiotics called cefazolin.\nYou need to continue this medication until [**2203-12-5**].\n\n\nFollowu

In [59]:
DIAGNOSES_ICD[['ICD9_CODE','HADM_ID']]

       ICD9_CODE  HADM_ID
0          40301   172335
1            486   172335
2          58281   172335
3           5855   172335
4           4254   172335
...          ...      ...
651042     20280   188195
651043     V5869   188195
651044     V1279   188195
651045      5275   188195
651046      5569   188195

[651047 rows x 2 columns]

In [60]:
NOTEEVENTS[['TEXT','HADM_ID']]

                                                      TEXT   HADM_ID
0        Admission Date:  [**2151-7-16**]       Dischar...  167853.0
1        Admission Date:  [**2118-6-2**]       Discharg...  107527.0
2        Admission Date:  [**2119-5-4**]              D...  167118.0
3        Admission Date:  [**2124-7-21**]              ...  196489.0
4        Admission Date:  [**2162-3-3**]              D...  135453.0
...                                                    ...       ...
2083175  NPN\n\n\n#1  Infant remains in RA with O2 sats...  115637.0
2083176  Neonatology\nDOL #5, CGA 36 weeks.\n\nCVR: Con...  115637.0
2083177  Family Meeting Note\nFamily meeting held with ...  115637.0
2083178  NPN 1800\n\n\n#1 Resp: [**Known lastname 2243*...  115637.0
2083179  NPN 1800\nNursing Addendum:\n[**Known lastname...  115637.0

[2083180 rows x 2 columns]

In [63]:
NOTE_DIAGNOSES_2=pd.merge(NOTEEVENTS,DIAGNOSES_ICD[['HADM_ID','ICD9_CODE']],on='HADM_ID')

In [64]:
NOTE_DIAGNOSES_2.head()

,ROW_ID,SUBJECT_ID,HADM_ID,CHARTDATE,CHARTTIME,STORETIME,CATEGORY,DESCRIPTION,CGID,ISERROR,TEXT,ICD9_CODE
0,174,22532,167853.0,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,01193
1,174,22532,167853.0,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,4254
2,174,22532,167853.0,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,42731
3,174,22532,167853.0,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,2639
4,174,22532,167853.0,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,2762

In [69]:
NOTE_DIAGNOSES_2.ICD9_CODE.nunique()

6967

In [70]:
NOTE_DIAGNOSES_2.HADM_ID.nunique()

58361

In [71]:
NOTE_DIAGNOSES_2[['HADM_ID','TEXT','ICD9_CODE']]

,HADM_ID,TEXT,ICD9_CODE
0,167853.0,Admission Date: [**2151-7-16**] Dischar...,01193
1,167853.0,Admission Date: [**2151-7-16**] Dischar...,4254
2,167853.0,Admission Date: [**2151-7-16**] Dischar...,42731
3,167853.0,Admission Date: [**2151-7-16**] Dischar...,2639
4,167853.0,Admission Date: [**2151-7-16**] Dischar...,2762
...,...,...,...
25736043,175166.0,Neonatology\nBaby Girl [**Known lastname 1672*...,V053
25736044,175166.0,Neonatology\nBaby Girl [**Known lastname 1672*...,V290
25736045,175166.0,NPN NICU\nTerm female admitted to NICU for sep...,V3001
25736046,175166.0,NPN NICU\nTerm female admitted to NICU for sep...,V053
25736047,175166.0,NPN NICU\nTerm female admitted to NICU for sep...,V290

In [91]:
NOTE_DIAGNOSES_2.loc[NOTE_DIAGNOSES_2['ICD9_CODE'] == '01193']

,ROW_ID,SUBJECT_ID,HADM_ID,CHARTDATE,CHARTTIME,STORETIME,CATEGORY,DESCRIPTION,CGID,ISERROR,TEXT,ICD9_CODE
0,174,22532,167853.0,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,01193
8,170,22532,167853.0,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,01193
16,59795,22532,167853.0,2151-08-02,NaN,NaN,Echo,Report,NaN,NaN,PATIENT/TEST INFORMATION:\nIndication: Aortic ...,01193
24,59796,22532,167853.0,2151-07-19,NaN,NaN,Echo,Report,NaN,NaN,PATIENT/TEST INFORMATION:\nIndication: Endocar...,01193
32,106289,22532,167853.0,2151-08-03,NaN,NaN,ECG,Report,NaN,NaN,Atrial fibrillation with a slow ventricular re...,01193
40,106290,22532,167853.0,2151-07-17,NaN,NaN,ECG,Report,NaN,NaN,Atrial fibrillation with a slow ventricular re...,01193
48,106291,22532,167853.0,2151-07-16,NaN,NaN,ECG,Report,NaN,NaN,Atrial fibrillation with a slow ventricular re...,01193
56,106292,22532,167853.0,2151-07-16,NaN,NaN,ECG,Report,NaN,NaN,Atrial fibrillation with a rapid ventricular r...,01193
64,763295,22532,167853.0,2151-07-16,2151-07-16 05:01:00,NaN,Radiology,CHEST (PORTABLE AP),NaN,NaN,[**2151-7-16**] 5:01 AM\n CHEST (PORTABLE AP) ...,01193
72,764802,22532,167853.0,2151-08-04,2151-08-04 15:39:00,NaN,Radiology,CT ABDOMEN W/CONTRAST,NaN,NaN,[**2151-8-4**] 3:39 PM\n CT ABDOMEN W/CONTRAST...,01193
80,764801,22532,167853.0,2151-08-04,2151-08-04 15:38:00,NaN,Radiology,CT HEAD W/ & W/O CONTRAST,NaN,NaN,[**2151-8-4**] 3:38 PM\n CT HEAD W/ & W/O CONT...,01193
88,764358,22532,167853.0,2151-07-29,2151-07-29 15:02:00,NaN,Radiology,CHEST (PA & LAT),NaN,NaN,[**2151-7-29**] 3:02 PM\n CHEST (PA & LAT) ...,01193
96,764613,22532,167853.0,2151-08-02,2151-08-02 14:32:00,NaN,Radiology,CHEST (PA & LAT),NaN,NaN,[**2151-8-2**] 2:32 PM\n CHEST (PA & LAT) ...,01193
104,763324,22532,167853.0,2151-07-16,2151-07-16 10:10:00,NaN,Radiology,CHEST (PORTABLE AP),NaN,NaN,[**2151-7-16**] 10:10 AM\n CHEST (PORTABLE AP)...,01193
112,764165,22532,167853.0,2151-07-27,2151-07-27 09:21:00,NaN,Radiology,CHEST (PORTABLE AP),NaN,NaN,[**2151-7-27**] 9:21 AM\n CHEST (PORTABLE AP) ...,01193
120,763401,22532,167853.0,2151-07-17,2151-07-17 06:15:00,NaN,Radiology,CHEST (PORTABLE AP),NaN,NaN,[**2151-7-17**] 6:15 AM\n CHEST (PORTABLE AP) ...,01193
128,763498,22532,167853.0,2151-07-18,2151-07-18 16:50:00,NaN,Radiology,CT CHEST W/CONTRAST,NaN,NaN,[**2151-7-18**] 4:50 PM\n CT CHEST W/CONTRAST;...,01193
136,763415,22532,167853.0,2151-07-17,2151-07-17 12:03:00,NaN,Radiology,PELVIS PORTABLE,NaN,NaN,[**2151-7-17**] 12:03 PM\n PELVIS PORTABLE ...,01193
144,763371,22532,167853.0,2151-07-16,2151-07-16 19:11:00,NaN,Radiology,CHEST (PORTABLE AP),NaN,NaN,[**2151-7-16**] 7:11 PM\n CHEST (PORTABLE AP) ...,01193
152,763789,22532,167853.0,2151-07-22,2151-07-22 09:54:00,NaN,Radiology,CHEST (PORTABLE AP),NaN,NaN,[**2151-7-22**] 9:54 AM\n CHEST (PORTABLE AP) ...,01193
160,763898,22532,167853.0,2151-07-23,2151-07-23 13:43:00,NaN,Radiology,LUNBAR SPINAL PUNCTURE,NaN,NaN,[**2151-7-23**] 1:43 PM\n [**Numeric Identifie...,01193
168,763335,22532,167853.0,2151-07-16,2151-07-16 11:24:00,NaN,Radiology,P CHEST (LAT DECUB ONLY) PORT,NaN,NaN,[**2151-7-16**] 11:24 AM\n CHEST (LAT DECUB ON...,01193
176,1556854,22532,167853.0,2151-07-18,2151-07-18 14:01:00,2151-07-18 14:06:00,Nursing/other,Report,21570,NaN,"resp note:spont mechanics(NIF,VC)performed by ...",01193
184,1556855,22532,167853.0,2151-07-18,2151-07-18 18:53:00,2151-07-18 19:00:00,Nursing/other,Report,16021,NaN,pmicu nursing progress note\ncardiac: continu...,01193
192,1556856,22532,167853.0,2151-07-19,2151-07-19 04:53:00,2151-07-19 05:10:00,Nursing/other,Report,18679,NaN,NPN-MICU\nMrs.[**Known lastname **] has remain...,01193
200,1556857,22532,167853.0,2151-07-19,2151-07-19 16:32:00,2151-07-19 16:38:00,Nursing/other,Report,21570,NaN,NURSING PROGRESS NOTE\n\nNEURO: ALERT AND ORIE...,01193
208,1556852,22532,167853.0,2151-07-17,2151-07-17 17:22:00,2151-07-17 17:42:00,Nursing/other,Report,16021,NaN,PMICU NURSING PROGRESS NOTE\nRESP: CHEST XRAY ...,01193
216,1556853,22532,167853.0,2151-07-18,2151-07-18 05:12:00,2151-07-18 05:41:00,Nursing/other,Report,18679,NaN,NPN-MICU\nMrs.[**Known lastname **] has done w...,01193
224,1556848,22532,167853.0,2151-07-16,2151-07-16 15:27:00,2151-07-16 15:36:00,Nursing/other,Report,20848,NaN,FOCUS; ADMISSION NOTE.\nRFA- MS CHANGES AND HO...,01193
232,1556849,22532,167853.0,2151-07-17,2151-07-17 02:05:00,2151-07-17 02:18:00,Nursing/other,Report,21570,NaN,"nsg progress notes\nneuro: very sleepy, arousa...",01193
240,1556850,22532,167853.0,2151-07-17,2151-07-17 05:36:00,2151-07-17 05:49:00,Nursing/other,Report,21570,NaN,addendum\ncardiac: troponin 14 at [**2149**] c...,01193
248,1556851,22532,167853.0,2151-07-17,2151-07-17 05:47:00,2151-07-17 05:49:00,Nursing/other,Report,21570,NaN,social: is a full code. grand daughter updated...,01193